# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Allow local connections
local   all             all                                     trust

# Allow connections from backend container via Docker network
host    all             all             0.0.0.0/0               md5
